name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build image and push to docker hub
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm start
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to Docker Hub
      id: docker_run
      uses: docker/build-push-action@v2.2.2
      with:
        push: true
        tags: dockerhub/latest:test
        context: .
        file: ./Dockerfile
    - name: Image digest
      run: echo ${{ steps.docker_run.outputs.digest }}

  copy-compose-dev:
    name: Copy dcoker-compose.yml to instance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy compose on instance via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.INSTANCE_SSH_HOST }}
          username: ${{ secrets.INSTANCE_SSH_USERNAME }}
          key: ${{ secrets.INSTANCE_SSH_KEY }}
          port: ${{ secrets.INSTANCE_SSH_PORT }}
          source: "docker-compose.yml"
          target: "test"

  pull-rm-up-dev:
    name: Pull image from dockerhub on dev machine and start it
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: start containers on dev machine via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_SSH_HOST }}
          username: ${{ secrets.INSTANCE_SSH_USERNAME }}
          key: ${{ secrets.INSTANCE_SSH_KEY }}
          port: ${{ secrets.INSTANCE_SSH_PORT }}
          script: |
            docker pull dockerhub/latest:test
            cd test && docker-compose --file docker-compose.yml up -d
